services:
  postgres:
    image: 'postgres:17.2'
    container_name: spring-boot-rest-api-boilerplate-postgres
    restart: always
    environment:
      - 'POSTGRES_DB=spring_rest'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=dbuser'
    ports:
      - '5434:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
